version: '3.8'
services:
  dev:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
      args:
        GID: ${MY_GID}
        UID: ${MY_UID}
  test:
    build:
      context: .
      target: test
      dockerfile: Dockerfile
  deploy:
    image: stf-deploy
    build:
      context: .
      target: deploy
      dockerfile: Dockerfile
    ports:
      - ${PORT_DEPLOY}:3500
