name: publish
on:
  workflow_run:
    workflows: ["test"]
    types: [completed]
    branches:
      - master
jobs:
  publish-app-image:
    runs-on: ubuntu-latest
    env:
      REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    steps:
      - uses: actions/checkout@v3
      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: $REGISTRY_URL
          username: ${{ secrets.REGISTRY_USER_NAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push image
        run: |
          docker-compose build deploy 
          docket tag stf-deploy:latest $REGISTRY_URL/stf:latest
          docker push $REGISTRY_URL/stf:latest