name: Publishing
on:
  workflow_run:
    workflows: [Testing]
    type: [completed]
    branches: [master]
jobs:
  publish-app-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      REGISTRY_URL: ghcr.io
      REPO_NAME: ${{ github.repository }}
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    steps:
      - uses: actions/checkout@v3
      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and push image
        run: |
          docker-compose build deploy 
          docker tag stf-deploy:latest $REGISTRY_URL/$REPO_NAME/stf:latest
          docker push $REGISTRY_URL/$REPO_NAME/stf:latest
