name: Testing
on: [push]
jobs:
  test-app:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
      CODACY_TOKEN: ${{ secrents.CODACY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Build test image
        run: |
          docker-compose build --build-arg CODACY_TOKEN="$CODACY_TOKEN" test
          