name: Testing
on: [push]
jobs:
  test-app:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Build test image
        run: |
          docker-compose build test
      - name: Upload coverage report
        if: github.ref == 'refs/heads/master'
        run: |
          docker-compose run test bash -c "bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r ./coverage.xml"
          